# Generated by Django 4.1.4 on 2023-02-11 17:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlEgresos',
            fields=[
                ('id', models.AutoField(default=1000, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('empresa', models.IntegerField(choices=[(1, 'FloralGroup'), (2, 'FloralCargo'), (3, 'FloralHome')])),
                ('nombre', models.CharField(max_length=255)),
                ('concepto', models.CharField(max_length=255)),
                ('categoria', models.IntegerField(choices=[(1, 'marketing'), (2, 'nomina'), (3, 'mercancias'), (4, 'contabilidad'), (5, 'fletes'), (6, 'impuestos'), (7, 'vehiculos'), (8, 'cafeteria'), (9, 'servicios publicos'), (10, 'bodega'), (11, 'oficina'), (12, 'prestamos'), (13, 'aseo'), (14, 'arriendos'), (15, 'otros')])),
                ('medio_pago', models.IntegerField(choices=[(1, 'nequi'), (2, 'daviplata_jf'), (3, 'efectivo'), (4, 'daviplata_dc'), (5, 'bancolombia_cargo'), (6, 'bancolombia_home'), (7, 'tc_bancolombia'), (8, 'bancolombia_aho_fg'), (9, 'bancolombia_cte_fg')])),
                ('valor', models.FloatField(default=0)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'egresos_controlegresos',
                'managed': True,
            },
        ),
    ]
