# Generated by Django 4.1.4 on 2023-02-11 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegresos',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
