# Generated by Django 4.1.4 on 2023-02-11 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('egresos', '0002_alter_controlegresos_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controlegresos',
            name='id',
            field=models.AutoField(default=1000, primary_key=True, serialize=False),
        ),
    ]
